# Generated by Django 5.0.8 on 2024-08-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Приветственный текст')),
            ],
            options={
                'verbose_name': 'Приветственный текст',
                'verbose_name_plural': 'Приветственный текст',
            },
        ),
        migrations.CreateModel(
            name='Parting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Завершающий текст')),
            ],
            options={
                'verbose_name': 'Завершающий текст',
                'verbose_name_plural': 'Завершающий текст',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('tg_id', models.BigIntegerField(verbose_name='Телеграм ID')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer_view', models.IntegerField(choices=[(0, 'Оценочная шкала'), (1, 'Комментарий'), (2, 'Да/Нет')], default=0, verbose_name='Вид ответа')),
                ('trigger', models.CharField(choices=[('1,2,3', '1,2,3'), ('1,2,3,4', '1,2,3,4'), ('4,5', '4,5'), ('5', '5'), ('Да', 'Да'), ('Нет', 'Нет')], default=0, help_text='Выберите триггер по кототорому будет задаваться связанный вопрос', max_length=255, verbose_name='Триггер')),
                ('add_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_app_2.question', verbose_name='Связанный вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yon', models.BooleanField(blank=True, default=False, null=True, verbose_name='Да/Нет')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app_2.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app_2.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
